// <auto-generated />
using System;
using Academia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academia.Migrations
{
    [DbContext(typeof(AcademiaContext))]
    partial class AcademiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Academia.Moldls.Inscripto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Profesorid")
                        .HasColumnType("int");

                    b.Property<int?>("RitmoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Profesorid");

                    b.HasIndex("RitmoId");

                    b.ToTable("inscriptos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Edad = "21",
                            Nombre = "Sofia"
                        },
                        new
                        {
                            Id = 2,
                            Edad = "21",
                            Nombre = "Lara"
                        });
                });

            modelBuilder.Entity("Academia.Moldls.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profesores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Maria"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Karen"
                        });
                });

            modelBuilder.Entity("Academia.Moldls.Ritmo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ritmos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Clasico"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Cumbia"
                        });
                });

            modelBuilder.Entity("Academia.Moldls.Inscripto", b =>
                {
                    b.HasOne("Academia.Moldls.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("Profesorid");

                    b.HasOne("Academia.Moldls.Ritmo", "Ritmo")
                        .WithMany()
                        .HasForeignKey("RitmoId");

                    b.Navigation("Profesor");

                    b.Navigation("Ritmo");
                });
#pragma warning restore 612, 618
        }
    }
}
